### PR TITLE
GUI support for tools. More tools from langchain.

### PR DESCRIPTION
**Pull request by IggoOnCode**
Added "requests" to the array of enabled tools, to give the model the ability to use the web including APIs.

Changed the used description to the description directly from the tools instead of own array with descriptions.

This way all tools from langchain should be easily enabled. (But I only tested requests.)

### CODE REVIEW

**Comment by cornpo** [comment]
term



Be careful with REPL, I think.

**Comment by flurb18** [comment]
I started using custom descriptions because the given ones weren't doing it, the model needs very specific instructions on what the tool can do. I'll include a way to use the default descriptions or provide custom descriptions based on preference.

**Comment by IggoOnCode** [comment]
Then I will try to build a selector for the tools and default/custom descriptions into the UI.

**Comment by IggoOnCode** [comment]
Hi @flurb18 

I made the tools selectable in the GUI, including custom descriptions in the GUI with custom defaults or langchain defaults.

**Comment by IggoOnCode** [comment]
@flurb18 I think it's ready for review now. Will wait for your feedback before doing more on it.

**Comment by flurb18** [comment]
Reviewing now! Thanks!

**Comment by flurb18** [comment]
Merged. Good changes, I think the vision for this project is as customizable as possible. Thanks again!

**Comment by IggoOnCode** [comment]
Thanks for merging!

I'll try to bring even more tools in. And maybe add saving for the changed descriptions.

**Comment by flurb18** [comment]
I moved stuff around a little bit, made it all into one dictionary in the AgentOobaVars dict. Works the same.

**Pull request merged**
